language: r
sudo: required

# Be strict when checking our package
warnings_are_errors: true

install:
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get remove -y libgdal1
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install python-numpy python-scipy python-gdal libgdal-dev python-mpltoolkits.basemap
  - pip install .
